---

- hosts: all
  become: true
  tasks:

  - name: update repository index by lee
    apt:
      update_cache: yes

  - name: install apache2 package by lee
    apt:
      name: apache2 
      state: latest

  - name: install next one dude
    apt:
      name: libapache2-mod-php 
      state: latest
