---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package by lee
    apt:
      name: apache2
      state: absent

  - name: install next one dude
    apt:
      name: libapache2-mod-php 
      state: absent

